# =====================================================
# Cata Log API — Perfil de Desenvolvimento
# =====================================================

# Ativa logs SQL para debug
spring.jpa.show-sql=true

# Logs detalhados
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.flywaydb=DEBUG
